### ISSUE TITLE
Whitelabel Error Page

### ISSUE THREAD

**Issue by yuriscosta-zz** [SpringWithNataniel/aula2#1]
Quando eu executo o seu exemplo funciona, mas, quando faço um do 0 seguindo o que você fez, um erro é mostrado na página.

```
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Mon Oct 02 03:11:40 BRT 2017
There was an unexpected error (type=Not Found, status=404).
No message available
```

Já tentei de tudo pra resolver isso e não consegui.

**Comment by yuriscosta-zz** [comment]
@natanielpaiva

**Comment by natanielpaiva** [comment]
Você está rodando em algum servidor de aplicação? Sem que seja o Tomcat ?

**Comment by yuriscosta-zz** [comment]
Não selecionei o apache tomcat quando criei o projeto. Tenho que selecioná-lo? Foi pq eu fiz que nem você fez na aula 01.

**Comment by natanielpaiva** [comment]
Você criou a classe IndexController? Com o @RequestMapping(value="/")?

**Comment by yuriscosta-zz** [comment]
Sim. Quando eu acesso a raiz ele mostra normal, mas quando eu tento acessar /usuario aí dá esse erro.
Testei aqui agora com o apache tomcat e continua assim.

**Comment by yuriscosta-zz** [comment]
```
@RestController
public class UsuarioController {

    @Autowired
    UsuarioService usuarioService;

    @RequestMapping(value = "/usuario", method = RequestMethod.POST)
    public List<Usuario> listUsuario() {
        return this.usuarioService.listaUsuario();
    }

    @RequestMapping(value = "/usuario", method = RequestMethod.POST)
    public List<Usuario> listUsuario(@RequestBody Usuario usuario) {
        return this.usuarioService.listaUsuario(usuario);
    }
}
```

**Comment by yuriscosta-zz** [comment]
Quando eu baixo o seu projeto e executo funciona normal, mas quando faço o meu não.
Vou mandar o meu projeto zipado para que você teste aí.
[aula02.zip](https://github.com/SpringWithNataniel/aula2/files/1351183/aula02.zip)

**Comment by natanielpaiva** [comment]
Só tem um erro no seu código:

@RestController
public class UsuarioController {

    @Autowired
    UsuarioService usuarioService;

    //nessa linha abaixo é get
    @RequestMapping(value = "/usuario", method = RequestMethod.GET)
    public List<Usuario> listUsuario() {
        return this.usuarioService.listaUsuario();
    }

    @RequestMapping(value = "/usuario", method = RequestMethod.POST)
    public List<Usuario> listUsuario(@RequestBody Usuario usuario) {
        return this.usuarioService.listaUsuario(usuario);
    }
}

**Comment by yuriscosta-zz** [comment]
Mesmo colocando o GET não funciona. Você testou aí?

**Comment by natanielpaiva** [comment]
Fez o clean build?

**Comment by yuriscosta-zz** [comment]
Fiz

**Comment by natanielpaiva** [comment]
Pronto!!
https://www.youtube.com/watch?v=4RHgLRJz8x8&feature=youtu.be

**Comment by yuriscosta-zz** [comment]
Agora funcionou. Obrigado pela paciência. 😄

**Comment by natanielpaiva** [comment]
Nada! Fico feliz em ajudar! Se estiver gostando do curso, por favor me ajude lá na avaliação, e se tiver algum feedback fique a vontade para me enviar mensagem pelo Udemy. Abraços
